/**
 * Generates src/components/icons.tsx from the local Phosphor icon pack.
 * Run: node scripts/gen-icons.mjs   (add/renumber in ICONS below)
 */
import { readFileSync, writeFileSync } from 'node:fs';

const PACK = 'C:/Users/sloth/Downloads/phosphor-icons/SVGs';

const ICONS = [
  ['Gauge', 'duotone/gauge-duotone.svg'],
  ['PenNib', 'duotone/pen-nib-duotone.svg'],
  ['ClipboardText', 'duotone/clipboard-text-duotone.svg'],
  ['ChartPie', 'duotone/chart-pie-duotone.svg'],
  ['History', 'duotone/clock-counter-clockwise-duotone.svg'],
  ['FileText', 'duotone/file-text-duotone.svg'],
  ['Gear', 'duotone/gear-duotone.svg'],
  ['Users', 'duotone/users-duotone.svg'],
  ['Signature', 'duotone/signature-duotone.svg'],
  ['SealCheck', 'duotone/seal-check-duotone.svg'],
  ['Hourglass', 'duotone/hourglass-duotone.svg'],
  ['FloppyDisk', 'duotone/floppy-disk-duotone.svg'],
  ['SignOut', 'duotone/sign-out-duotone.svg'],
  ['Warning', 'duotone/warning-duotone.svg'],
  ['PencilSimple', 'duotone/pencil-simple-duotone.svg'],
  ['Star', 'fill/star-fill.svg'],
];

function toJsxInner(svg) {
  // body between <svg ...> and </svg>
  let inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '');
  // drop the transparent background rect
  inner = inner.replace(/<rect width="256" height="256" fill="none"\s*\/>/, '');
  // camelCase JSX attributes
  inner = inner
    .replace(/stroke-width=/g, 'strokeWidth=')
    .replace(/stroke-linecap=/g, 'strokeLinecap=')
    .replace(/stroke-linejoin=/g, 'strokeLinejoin=')
    .replace(/stroke-miterlimit=/g, 'strokeMiterlimit=')
    .replace(/fill-rule=/g, 'fillRule=')
    .replace(/clip-rule=/g, 'clipRule=');
  // any drawn element without a fill gets currentColor (duotone underlay)
  inner = inner.replace(
    /<(path|rect|circle|line|polygon|polyline)((?:(?!fill=)[^>])*)\/>/g,
    (_, tag, attrs) => `<${tag} fill="currentColor"${attrs} />`,
  );
  return inner.trim();
}

const parts = [
  '// Generated by scripts/gen-icons.mjs from the local Phosphor pack (MIT).',
  '// Phosphor Icons — https://phosphoricons.com — do not edit by hand.',
  '',
  'type IconProps = { className?: string };',
  '',
];

for (const [name, file] of ICONS) {
  const svg = readFileSync(`${PACK}/${file}`, 'utf8');
  const inner = toJsxInner(svg);
  if (!inner) throw new Error(`empty icon: ${file}`);
  parts.push(
    `export function Icon${name}({ className = 'h-5 w-5' }: IconProps) {`,
    '  return (',
    `    <svg viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" className={className}>`,
    `      ${inner}`,
    '    </svg>',
    '  );',
    '}',
    '',
  );
  console.log('ok', name);
}

writeFileSync('src/components/icons.tsx', parts.join('\n'));
console.log(`\nwrote src/components/icons.tsx (${ICONS.length} icons)`);
