-- 0001: row level security, auth trigger, views, RPC functions
-- Runs after the 0000_* file generated by drizzle-kit.
-- All app data access goes through the authenticated user's JWT (PostgREST),
-- so these policies are the actual authorization layer.

-- ═══════════════════════ helpers ═══════════════════════

-- security definer so policies on profiles can call this without recursion
create or replace function public.current_role()
returns public.role
language sql stable security definer set search_path = public
as $$ select role from public.profiles where id = auth.uid() $$;

-- auto-create a profile whenever an auth user is created
create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, role, full_name, student_no)
  values (
    new.id,
    coalesce((new.raw_user_meta_data->>'role')::public.role, 'student'),
    coalesce(new.raw_user_meta_data->>'full_name', new.email),
    nullif(new.raw_user_meta_data->>'student_no', '')
  );
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- ═══════════════════════ RLS ═══════════════════════

alter table public.profiles           enable row level security;
alter table public.programs           enable row level security;
alter table public.sections           enable row level security;
alter table public.semesters          enable row level security;
alter table public.subjects           enable row level security;
alter table public.questions          enable row level security;
alter table public.section_subjects   enable row level security;
alter table public.enrollments        enable row level security;
alter table public.evaluations        enable row level security;
alter table public.evaluation_answers enable row level security;

revoke all on all tables in schema public from anon;

-- profiles: readable by any signed-in user (names are needed everywhere);
-- writable by own user or admin
create policy profiles_select on public.profiles
  for select to authenticated using (true);
create policy profiles_update_own on public.profiles
  for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());
create policy profiles_update_admin on public.profiles
  for update to authenticated
  using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

-- reference tables: read = any signed-in user, write = admin only
create policy programs_select on public.programs for select to authenticated using (true);
create policy programs_admin   on public.programs for all to authenticated
  using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

create policy sections_select on public.sections for select to authenticated using (true);
create policy sections_admin  on public.sections for all to authenticated
  using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

create policy semesters_select on public.semesters for select to authenticated using (true);
create policy semesters_admin  on public.semesters for all to authenticated
  using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

create policy subjects_select on public.subjects for select to authenticated using (true);
create policy subjects_admin  on public.subjects for all to authenticated
  using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

create policy questions_select on public.questions for select to authenticated using (true);
create policy questions_admin  on public.questions for all to authenticated
  using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

create policy section_subjects_select on public.section_subjects for select to authenticated using (true);
create policy section_subjects_admin  on public.section_subjects for all to authenticated
  using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

-- enrollments: student sees own, faculty sees own classes, dean/admin see all, admin writes
create policy enrollments_student on public.enrollments
  for select to authenticated using (student_id = auth.uid());
create policy enrollments_faculty on public.enrollments
  for select to authenticated using (
    exists (select 1 from public.section_subjects ss
            where ss.id = enrollments.section_subject_id and ss.faculty_id = auth.uid())
  );
create policy enrollments_dean on public.enrollments
  for select to authenticated using (public.current_role() in ('dean', 'admin'));
create policy enrollments_admin on public.enrollments
  for all to authenticated
  using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

-- evaluations: student sees/submits own; dean/admin see all;
-- faculty NEVER gets direct select (student identity must stay hidden) —
-- they read through the faculty_evaluations view below
create policy evaluations_student_select on public.evaluations
  for select to authenticated using (student_id = auth.uid());
create policy evaluations_dean_select on public.evaluations
  for select to authenticated using (public.current_role() in ('dean', 'admin'));
create policy evaluations_student_insert on public.evaluations
  for insert to authenticated with check (
    student_id = auth.uid()
    and exists (select 1 from public.enrollments e
                where e.id = enrollment_id and e.student_id = auth.uid())
  );
-- no update, no delete — evaluations are immutable once submitted

-- evaluation_answers follow the same shape
create policy answers_student_select on public.evaluation_answers
  for select to authenticated using (
    exists (select 1 from public.evaluations e
            where e.id = evaluation_answers.evaluation_id and e.student_id = auth.uid())
  );
create policy answers_faculty_select on public.evaluation_answers
  for select to authenticated using (
    exists (select 1 from public.evaluations e
            join public.section_subjects ss on ss.id = e.section_subject_id
            where e.id = evaluation_answers.evaluation_id and ss.faculty_id = auth.uid())
  );
create policy answers_dean_select on public.evaluation_answers
  for select to authenticated using (public.current_role() in ('dean', 'admin'));
create policy answers_student_insert on public.evaluation_answers
  for insert to authenticated with check (
    exists (select 1 from public.evaluations e
            where e.id = evaluation_id and e.student_id = auth.uid())
  );

alter table public.evaluation_answers
  add constraint answers_rating_check check (rating between 1 and 5);

-- ═══════════════════════ views ═══════════════════════

-- student's assigned subjects + completion status (own rows only)
create or replace view public.student_evals as
select ss.id as section_subject_id,
       ss.semester_id,
       sub.code as subject_code,
       sub.name as subject_name,
       sec.name as section_name,
       sec.year_level,
       p.full_name as faculty_name,
       s.is_open,
       s.closes_at,
       e.id as evaluation_id
from public.enrollments en
join public.section_subjects ss on ss.id = en.section_subject_id
join public.subjects sub on sub.id = ss.subject_id
join public.sections sec on sec.id = ss.section_id
join public.profiles p on p.id = ss.faculty_id
join public.semesters s on s.id = ss.semester_id
left join public.evaluations e on e.enrollment_id = en.id
where en.student_id = auth.uid();
grant select on public.student_evals to authenticated;

-- faculty's own evaluation results — no student identity columns, ever
create or replace view public.faculty_evaluations as
select e.id,
       e.section_subject_id,
       e.semester_id,
       e.comment,
       e.sentiment_label,
       e.sentiment_score,
       e.submitted_at,
       sub.code as subject_code,
       sub.name as subject_name,
       sec.name as section_name
from public.evaluations e
join public.section_subjects ss on ss.id = e.section_subject_id
join public.subjects sub on sub.id = ss.subject_id
join public.sections sec on sec.id = ss.section_id
where ss.faculty_id = auth.uid();
grant select on public.faculty_evaluations to authenticated;

-- ═══════════════════════ RPC functions ═══════════════════════
-- All are SECURITY INVOKER (default): every table access inside re-checks
-- the caller's RLS policies, so a function never exposes more than the
-- caller is allowed to see.

create or replace function public.rpc_student_dashboard()
returns jsonb language sql stable as $$
  with cur as (
    select * from public.semesters where is_current
    order by academic_year desc, term desc limit 1
  )
  select jsonb_build_object(
    'current_semester', (select to_jsonb(cur) from cur),
    'subjects', (select coalesce(jsonb_agg(row_to_json(t) order by t.subject_code), '[]'::jsonb) from (
      select v.section_subject_id, v.subject_code, v.subject_name, v.section_name,
             v.faculty_name, v.is_open, v.closes_at,
             v.evaluation_id is not null as completed
      from public.student_evals v cross join cur
      where v.semester_id = cur.id
    ) t),
    'past', (select coalesce(jsonb_agg(t), '[]'::jsonb) from (
      select v.semester_id, s.academic_year, s.term,
             count(*) filter (where v.evaluation_id is not null) as completed,
             count(*) as total
      from public.student_evals v
      join public.semesters s on s.id = v.semester_id
      cross join cur
      where v.semester_id <> cur.id
      group by v.semester_id, s.academic_year, s.term
    ) t)
  );
$$;

create or replace function public.rpc_faculty_overview(p_semester_id uuid default null)
returns jsonb language sql stable as $$
  select jsonb_build_object(
    'per_question', (select coalesce(jsonb_agg(row_to_json(t) order by t.sort_order), '[]'::jsonb) from (
      select q.id, q.text, q.category, q.sort_order,
             round(avg(a.rating)::numeric, 2)::float8 as avg_rating,
             count(a.id)::int as responses
      from public.faculty_evaluations fe
      join public.evaluation_answers a on a.evaluation_id = fe.id
      join public.questions q on q.id = a.question_id
      where p_semester_id is null or fe.semester_id = p_semester_id
      group by q.id
    ) t),
    'per_subject', (select coalesce(jsonb_agg(row_to_json(t)), '[]'::jsonb) from (
      select fe.subject_code, fe.subject_name, fe.section_name,
             count(distinct fe.id)::int as evals,
             round(avg(a.rating)::numeric, 2)::float8 as avg_rating
      from public.faculty_evaluations fe
      join public.evaluation_answers a on a.evaluation_id = fe.id
      where p_semester_id is null or fe.semester_id = p_semester_id
      group by fe.subject_code, fe.subject_name, fe.section_name
    ) t),
    'sentiment', (select jsonb_build_object(
        'positive', count(*) filter (where sentiment_label = 'positive'),
        'neutral',  count(*) filter (where sentiment_label = 'neutral'),
        'negative', count(*) filter (where sentiment_label = 'negative')
      ) from public.faculty_evaluations
      where p_semester_id is null or semester_id = p_semester_id),
    'comments', (select coalesce(jsonb_agg(row_to_json(t) order by t.at desc), '[]'::jsonb) from (
      select comment, sentiment_label as label, submitted_at as at
      from public.faculty_evaluations
      where (p_semester_id is null or semester_id = p_semester_id)
        and comment is not null
    ) t),
    'overall', (select round(avg(a.rating)::numeric, 2)::float8
      from public.faculty_evaluations fe
      join public.evaluation_answers a on a.evaluation_id = fe.id
      where p_semester_id is null or fe.semester_id = p_semester_id)
  );
$$;

create or replace function public.rpc_dean_overview(p_semester_id uuid default null)
returns jsonb language sql stable as $$
  with sid as (
    select coalesce(p_semester_id, (select id from public.semesters where is_current limit 1)) as id
  )
  select jsonb_build_object(
    'semester', (select to_jsonb(s) from public.semesters s cross join sid where s.id = sid.id),
    'participation', (select jsonb_build_object(
        'enrolled', (select count(distinct en.student_id)::int
                     from public.enrollments en
                     join public.section_subjects ss on ss.id = en.section_subject_id
                     cross join sid where ss.semester_id = sid.id),
        'submitted', (select count(distinct e.student_id)::int
                      from public.evaluations e cross join sid where e.semester_id = sid.id),
        'total_evals', (select count(*)::int
                        from public.evaluations e cross join sid where e.semester_id = sid.id)
      )),
    'faculty', (select coalesce(jsonb_agg(row_to_json(t) order by t.overall desc nulls last), '[]'::jsonb) from (
      select p.id, p.full_name,
             count(distinct ss.id)::int as loads,
             count(distinct e.id)::int as evals,
             round(avg(a.rating)::numeric, 2)::float8 as overall
      from public.profiles p
      cross join sid
      left join public.section_subjects ss on ss.faculty_id = p.id and ss.semester_id = sid.id
      left join public.evaluations e on e.section_subject_id = ss.id
      left join public.evaluation_answers a on a.evaluation_id = e.id
      where p.role = 'faculty'
      group by p.id, p.full_name
    ) t),
    'sentiment', (select jsonb_build_object(
        'positive', count(*) filter (where sentiment_label = 'positive'),
        'neutral',  count(*) filter (where sentiment_label = 'neutral'),
        'negative', count(*) filter (where sentiment_label = 'negative')
      ) from public.evaluations e cross join sid where e.semester_id = sid.id),
    'per_criterion', (select coalesce(jsonb_agg(row_to_json(t) order by t.category), '[]'::jsonb) from (
      select q.category, round(avg(a.rating)::numeric, 2)::float8 as avg_rating
      from public.evaluations e
      join public.evaluation_answers a on a.evaluation_id = e.id
      join public.questions q on q.id = a.question_id
      cross join sid
      where e.semester_id = sid.id
      group by q.category
    ) t)
  );
$$;

-- history drill-down: AY → term → subject → faculty → detail
create or replace function public.rpc_history(
  p_academic_year text default null,
  p_term public.semester_term default null,
  p_subject_id uuid default null,
  p_faculty_id uuid default null
)
returns jsonb language sql stable as $$
  select case
    when p_academic_year is null then (
      select coalesce(jsonb_agg(row_to_json(t) order by t.academic_year desc), '[]'::jsonb) from (
        select s.academic_year,
               count(distinct e.id)::int as evals,
               round(avg(a.rating)::numeric, 2)::float8 as avg_rating
        from public.semesters s
        left join public.evaluations e on e.semester_id = s.id
        left join public.evaluation_answers a on a.evaluation_id = e.id
        group by s.academic_year
      ) t)
    when p_term is null then (
      select coalesce(jsonb_agg(row_to_json(t)), '[]'::jsonb) from (
        select s.id as semester_id, s.term,
               count(distinct e.id)::int as evals,
               round(avg(a.rating)::numeric, 2)::float8 as avg_rating
        from public.semesters s
        left join public.evaluations e on e.semester_id = s.id
        left join public.evaluation_answers a on a.evaluation_id = e.id
        where s.academic_year = p_academic_year
        group by s.id, s.term
      ) t)
    when p_subject_id is null then (
      select coalesce(jsonb_agg(row_to_json(t)), '[]'::jsonb) from (
        select sub.id as subject_id, sub.code, sub.name,
               count(distinct e.id)::int as evals,
               round(avg(a.rating)::numeric, 2)::float8 as avg_rating
        from public.section_subjects ss
        join public.subjects sub on sub.id = ss.subject_id
        join public.semesters s on s.id = ss.semester_id
        left join public.evaluations e on e.section_subject_id = ss.id
        left join public.evaluation_answers a on a.evaluation_id = e.id
        where s.academic_year = p_academic_year and s.term = p_term
        group by sub.id, sub.code, sub.name
      ) t)
    when p_faculty_id is null then (
      select coalesce(jsonb_agg(row_to_json(t)), '[]'::jsonb) from (
        select p.id as faculty_id, p.full_name, ss.id as section_subject_id,
               sub.code, sec.name as section_name,
               count(distinct e.id)::int as evals,
               round(avg(a.rating)::numeric, 2)::float8 as avg_rating
        from public.section_subjects ss
        join public.subjects sub on sub.id = ss.subject_id
        join public.sections sec on sec.id = ss.section_id
        join public.profiles p on p.id = ss.faculty_id
        join public.semesters s on s.id = ss.semester_id
        left join public.evaluations e on e.section_subject_id = ss.id
        left join public.evaluation_answers a on a.evaluation_id = e.id
        where s.academic_year = p_academic_year and s.term = p_term
          and ss.subject_id = p_subject_id
        group by p.id, p.full_name, ss.id, sub.code, sec.name
      ) t)
    else (
      select jsonb_build_object(
        'per_question', (select coalesce(jsonb_agg(row_to_json(t) order by t.sort_order), '[]'::jsonb) from (
          select q.text, q.category, q.sort_order,
                 round(avg(a.rating)::numeric, 2)::float8 as avg_rating
          from public.evaluations e
          join public.evaluation_answers a on a.evaluation_id = e.id
          join public.questions q on q.id = a.question_id
          join public.section_subjects ss on ss.id = e.section_subject_id
          join public.semesters s on s.id = ss.semester_id
          where s.academic_year = p_academic_year and s.term = p_term
            and (p_subject_id is null or ss.subject_id = p_subject_id)
            and ss.faculty_id = p_faculty_id
          group by q.id
        ) t),
        'comments', (select coalesce(jsonb_agg(row_to_json(t) order by t.at desc), '[]'::jsonb) from (
          select e.comment, e.sentiment_label as label, e.submitted_at as at
          from public.evaluations e
          join public.section_subjects ss on ss.id = e.section_subject_id
          join public.semesters s on s.id = ss.semester_id
          where s.academic_year = p_academic_year and s.term = p_term
            and (p_subject_id is null or ss.subject_id = p_subject_id)
            and ss.faculty_id = p_faculty_id
            and e.comment is not null
        ) t)
      )
    )
  end;
$$;

create or replace function public.rpc_semester_trend()
returns jsonb language sql stable as $$
  select coalesce(jsonb_agg(row_to_json(t) order by t.academic_year, t.term), '[]'::jsonb) from (
    select s.id as semester_id, s.academic_year, s.term, s.is_current,
           (select count(*)::int from public.evaluations e where e.semester_id = s.id) as evals,
           (select round(avg(a.rating)::numeric, 2)::float8
              from public.evaluations e
              join public.evaluation_answers a on a.evaluation_id = e.id
              where e.semester_id = s.id) as avg_rating,
           (select count(*)::int from public.evaluations e
              where e.semester_id = s.id and e.sentiment_label = 'positive') as positive,
           (select count(*)::int from public.evaluations e
              where e.semester_id = s.id and e.sentiment_label = 'neutral') as neutral,
           (select count(*)::int from public.evaluations e
              where e.semester_id = s.id and e.sentiment_label = 'negative') as negative
    from public.semesters s
  ) t;
$$;

create or replace function public.rpc_sentiment_report(p_semester_id uuid default null)
returns jsonb language sql stable as $$
  with sid as (
    select coalesce(p_semester_id, (select id from public.semesters where is_current limit 1)) as id
  ),
  c as (
    select e.comment, e.sentiment_label, e.sentiment_score, e.anonymous, e.submitted_at,
           case when e.anonymous then null else sp.full_name end as student_name,
           p.full_name as faculty_name,
           sub.code as subject_code
    from public.evaluations e
    join public.section_subjects ss on ss.id = e.section_subject_id
    join public.subjects sub on sub.id = ss.subject_id
    join public.profiles p on p.id = ss.faculty_id
    left join public.profiles sp on sp.id = e.student_id
    cross join sid
    where e.semester_id = sid.id and e.comment is not null
  )
  select jsonb_build_object(
    'counts', (select jsonb_build_object(
        'positive', count(*) filter (where sentiment_label = 'positive'),
        'neutral',  count(*) filter (where sentiment_label = 'neutral'),
        'negative', count(*) filter (where sentiment_label = 'negative')
      ) from c),
    'comments', (select coalesce(jsonb_agg(row_to_json(t) order by t.submitted_at desc), '[]'::jsonb) from (
      select comment, sentiment_label as label, sentiment_score,
             anonymous, student_name, faculty_name, subject_code, submitted_at
      from c
    ) t)
  );
$$;

-- atomic eval submit: validates enrollment + open period + no duplicate,
-- then inserts evaluation + answers in one transaction. RLS still applies
-- to every insert (invoker rights).
create or replace function public.rpc_submit_evaluation(
  p_section_subject_id uuid,
  p_anonymous boolean,
  p_comment text,
  p_sentiment public.sentiment_label,
  p_sentiment_score numeric,
  p_signature jsonb,
  p_answers jsonb
)
returns jsonb
language plpgsql volatile as $$
declare
  v_enrollment public.enrollments;
  v_semester public.semesters;
  v_eval public.evaluations;
  v_count int;
begin
  select * into v_enrollment
  from public.enrollments
  where student_id = auth.uid() and section_subject_id = p_section_subject_id;

  if v_enrollment.id is null then
    return jsonb_build_object('ok', false, 'error', 'not_enrolled');
  end if;

  select s.* into v_semester
  from public.semesters s
  join public.section_subjects ss on ss.semester_id = s.id
  where ss.id = p_section_subject_id;

  if v_semester.id is null or not v_semester.is_open
     or v_semester.closes_at is null or now() > v_semester.closes_at then
    return jsonb_build_object('ok', false, 'error', 'period_closed');
  end if;

  select count(*) into v_count
  from public.evaluations
  where student_id = auth.uid() and section_subject_id = p_section_subject_id;

  if v_count > 0 then
    return jsonb_build_object('ok', false, 'error', 'already_submitted');
  end if;

  insert into public.evaluations (
    enrollment_id, student_id, section_subject_id, semester_id,
    anonymous, comment, sentiment_label, sentiment_score, signature_points
  ) values (
    v_enrollment.id, auth.uid(), p_section_subject_id, v_semester.id,
    p_anonymous, nullif(trim(p_comment), ''),
    coalesce(p_sentiment, 'neutral'), coalesce(p_sentiment_score, 0), p_signature
  )
  returning * into v_eval;

  insert into public.evaluation_answers (evaluation_id, question_id, rating)
  select v_eval.id,
         (a->>'question_id')::uuid,
         (a->>'rating')::int
  from jsonb_array_elements(p_answers) a
  where (a->>'rating')::int between 1 and 5
    and exists (select 1 from public.questions q
                where q.id = (a->>'question_id')::uuid and q.active);

  if not exists (select 1 from public.evaluation_answers where evaluation_id = v_eval.id) then
    raise exception 'no valid answers';
  end if;

  return jsonb_build_object('ok', true, 'evaluation_id', v_eval.id);
end $$;

grant execute on function public.rpc_student_dashboard() to authenticated;
grant execute on function public.rpc_faculty_overview(uuid) to authenticated;
grant execute on function public.rpc_dean_overview(uuid) to authenticated;
grant execute on function public.rpc_history(text, public.semester_term, uuid, uuid) to authenticated;
grant execute on function public.rpc_semester_trend() to authenticated;
grant execute on function public.rpc_sentiment_report(uuid) to authenticated;
grant execute on function public.rpc_submit_evaluation(uuid, boolean, text, public.sentiment_label, numeric, jsonb, jsonb) to authenticated;
